// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Piadas.Data;

#nullable disable

namespace Piadas.Migrations
{
    [DbContext(typeof(PiadasDbContext))]
    [Migration("20240828224309_bootstrap")]
    partial class bootstrap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Piadas.Models.piadas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("pergunta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("piadas");
                });
#pragma warning restore 612, 618
        }
    }
}
